### PR TITLE
Add Puli bindings

### PR DESCRIPTION
**Pull request by dhopkalo**
Simple change to add support puli.

I tested it and included into other my project work fine but may be it's need some ClassDiscoveryTest.php or something like this to test puli repo bindings exist ?

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Can you please make sure that the latest discovery (0.6.4) is installed? It fixes a crucial bug.

As for testing: no, I don't think it needs testing. It is configuration, like composer config.

**Comment by sagikazarmark** [comment]
Fixes #12 and #13

**Comment by Nyholm** [comment]
:+1:

**Comment by dhopkalo** [comment]
To update php-http/discovery (0.6.4) we need to update php-http/adapter-integration-tests composer.json what hard requires php-http/discovery ^0.5

We can temporary fork php-http/adapter-integration-tests and change there  ^0.5 -> ~0.6.4 then create pull request and rather than waiting for merging pull request we can temporary change repository link to forked php-http/adapter-integration-tests with fixed version of the php-http/discovery. If you want i will do it :)

We can't update php-http/discovery until php-http/adapter-integration-tests don't fix hard version ^0.5
php-http/adapter-integration-tests 0.2.x-dev requires php-http/discovery ^0.5 -> no matching package found.

**Comment by sagikazarmark** [comment]
Oh shit, really. Okay, then I will just merge this and resolve the integration test thing manually.

**Comment by dhopkalo** [comment]
Thx @sagikazarmark :+1:

**Pull request merged**
