### PR TITLE
Using latest version of discovery

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I wonder how we should do this. This will make the guzzle 5 adapter incompatible with the mailgun SDK for example.

**Comment by Nyholm** [comment]
I think we should merge this and release a new patch version. I'll send a PR to most other libraries depending on discovery to bump them to requiring 0.9 and make them release a patch version as well.

**Comment by sagikazarmark** [comment]
That will still easily end up in version conflict. What if we use version >0.8,<1.0?

**Comment by sagikazarmark** [comment]
That's probably problematic as well, as we can't make sure that BC will not break in MJZ versions.

**Comment by Nyholm** [comment]
yes. Sure it might be a version conflict. But that means we have to bump all discovery 0.8 to 0.9. 

I am currently waiting for a new patch release of guzzle5 adapter because I do already have version conflicts. https://github.com/Happyr/LinkedIn-API-client/pull/106

**Comment by sagikazarmark** [comment]
Alright then, let's get this merged.

**Comment by sagikazarmark** [comment]
v0.6.0 is tagged

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
